spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_ddd_kotlin
    username: admin
server:
  port: 8123
